config/routes.rb
Sewit::Application.routes.draw do
  resources :fabric_collections

  resources :companies
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :fabric_collections
end

app/models/fabric_collection.rb
class FabricCollection < ActiveRecord::Base
  belongs_to :company
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout 'application'
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  # GET /companies
  # GET /companies.xml
  def index
    set_tab :companies
    
    @companies = Company.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @companies }
    end
  end

  # GET /companies/1
  # GET /companies/1.xml
  def show
    @company = Company.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @company }
    end
  end

  # GET /companies/new
  # GET /companies/new.xml
  def new
    @company = Company.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @company }
    end
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])
  end

  # POST /companies
  # POST /companies.xml
  def create
    @company = Company.new(params[:company])

    respond_to do |format|
      if @company.save
        format.html { redirect_to(@company, :notice => 'Company was successfully created.') }
        format.xml  { render :xml => @company, :status => :created, :location => @company }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @company.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /companies/1
  # PUT /companies/1.xml
  def update
    @company = Company.find(params[:id])

    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to(@company, :notice => 'Company was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @company.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.xml
  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to(companies_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/fabric_collections_controller.rb
class FabricCollectionsController < ApplicationController
  # GET /fabric_collections
  # GET /fabric_collections.xml
  def index
    @fabric_collections = FabricCollection.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @fabric_collections }
    end
  end

  # GET /fabric_collections/1
  # GET /fabric_collections/1.xml
  def show
    @fabric_collection = FabricCollection.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @fabric_collection }
    end
  end

  # GET /fabric_collections/new
  # GET /fabric_collections/new.xml
  def new
    @fabric_collection = FabricCollection.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @fabric_collection }
    end
  end

  # GET /fabric_collections/1/edit
  def edit
    @fabric_collection = FabricCollection.find(params[:id])
  end

  # POST /fabric_collections
  # POST /fabric_collections.xml
  def create
    @fabric_collection = FabricCollection.new(params[:fabric_collection])

    respond_to do |format|
      if @fabric_collection.save
        format.html { redirect_to(@fabric_collection, :notice => 'Fabric collection was successfully created.') }
        format.xml  { render :xml => @fabric_collection, :status => :created, :location => @fabric_collection }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @fabric_collection.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /fabric_collections/1
  # PUT /fabric_collections/1.xml
  def update
    @fabric_collection = FabricCollection.find(params[:id])

    respond_to do |format|
      if @fabric_collection.update_attributes(params[:fabric_collection])
        format.html { redirect_to(@fabric_collection, :notice => 'Fabric collection was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @fabric_collection.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /fabric_collections/1
  # DELETE /fabric_collections/1.xml
  def destroy
    @fabric_collection = FabricCollection.find(params[:id])
    @fabric_collection.destroy

    respond_to do |format|
      format.html { redirect_to(fabric_collections_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/fabric_collections_helper.rb
module FabricCollectionsHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :website %><br />
    <%= f.text_field :website %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h2><%= link_to 'Companies', companies_path %> > <%= @company.name %></h2>

<%= link_to 'Cancel', @company %>

<%= render 'form' %>

app/views/companies/index.html.erb
<h1>Listing companies</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Website</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @companies.each do |company| %>
  <tr>
    <td><%= company.name %></td>
    <td><%= company.website %></td>
    <td><%= link_to 'Show', company %></td>
    <td><%= link_to 'Edit', edit_company_path(company) %></td>
    <td><%= link_to 'Destroy', company, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h2><%= link_to 'Companies', companies_path %> > New Company</h2>

<%= render 'form' %>

app/views/companies/show.html.erb
<h2><%= link_to 'Companies', companies_path %> > <%= @company.name %></h2>

<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_company_path(@company) %>

<p>
  <b>Name:</b>
  <%= @company.name %>
</p>

<p>
  <b>Website:</b>
  <%= @company.website %>
</p>

<div id="fabric-collection-list" class="relation-list">
  <h3>Fabric Collections</h3>
  <ul>
  <% @company.fabric_collections.each do |fabric_collection| %>
    <li><%= link_to fabric_collection.name, fabric_collection %></li>
  <% end %>
  </ul>
</div>

<div id="fabric-list" class="relation-list">
  <h3>Fabrics</h3>
  <ul>
  <% @company.fabric_collections.each do |fabric_collection| %>
    <li><%= link_to fabric_collection.name, fabric_collection %></li>
  <% end %>
  </ul>
</div>

<div id="spool-list" class="relation-list">
  <h3>Spools</h3>
  <ul>
  <% @company.fabric_collections.each do |fabric_collection| %>
    <li><%= link_to fabric_collection.name, fabric_collection %></li>
  <% end %>
  </ul>
</div>

app/views/fabric_collections/_form.html.erb
<%= form_for(@fabric_collection) do |f| %>
  <% if @fabric_collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fabric_collection.errors.count, "error") %> prohibited this fabric_collection from being saved:</h2>

      <ul>
      <% @fabric_collection.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :company_id %><br />
    <%= f.collection_select(:company_id, Company.all, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :website %><br />
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fabric_collections/edit.html.erb
<h2><%= link_to 'Collections', fabric_collections_path %> > <%= @fabric_collection.name %></h2>

<%= link_to 'Cancel', @fabric_collection %>

<%= render 'form' %>

app/views/fabric_collections/index.html.erb
<h1>Listing fabric_collections</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Company</th>
    <th>Website</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @fabric_collections.each do |fabric_collection| %>
  <tr>
    <td><%= fabric_collection.name %></td>
    <td><%= link_to fabric_collection.company.name, :controller => "companies", :action => "show", :id => fabric_collection.company_id %></td>
    <td><%= link_to 'Link', fabric_collection.website %></td>
    <td><%= link_to 'Show', fabric_collection %></td>
    <td><%= link_to 'Edit', edit_fabric_collection_path(fabric_collection) %></td>
    <td><%= link_to 'Destroy', fabric_collection, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Fabric collection', new_fabric_collection_path %>

app/views/fabric_collections/new.html.erb
<h2><%= link_to 'Collections', fabric_collections_path %> > New Fabric Collection</h2>

<%= render 'form' %>

app/views/fabric_collections/show.html.erb
<h2><%= link_to 'Collections', fabric_collections_path %> > <%= @fabric_collection.name %></h2>

<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_fabric_collection_path(@fabric_collection) %>

<p>
  <b>Name:</b>
  <%= @fabric_collection.name %>
</p>

<p>
  <b>Company:</b>
  <%= link_to @fabric_collection.company.name, :controller => "companies", :action => "show", :id => @fabric_collection.company_id%>
</p>

<p>
  <b>Website:</b>
  <%= link_to @fabric_collection.website, @fabric_collection.website %>
</p>

<p>
  <b>Description:</b>
  <%= @fabric_collection.description %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sewit</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
  
  <div id="page-header">
  
    <div>
      <h2><%= link_to "SewIt!", :controller => "companies" %></h2> <p>Keep track of your stuff.</p>
    </div>
  
    <% tabs_tag :open_tabs => { :id => "main-tabs", :class => "primary-tabnav" } do |tab| %>
      <%= tab.companies   'Companies',    "/companies" %>
      <%= tab.collections 'Collections',  "/fabric_collections" %>
    <% end %>
    
    <div class="clearfix"></div>
  
  </div>

<%= yield %>

</body>
</html>